{
 "title": "ArangoDB",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "ArangoDB" }
  ]
 },
 "panels": [
  {
   "title": "CreateDatabase Runtime",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_maintenance_action_runtime_msec_bucket{action=\"CreateDatabase\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heartbeat Roundtrip Time",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_heartbeat_send_time_msec_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Shard Distribution",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "arangodb_shards_total_count{type=\"dbservers\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dropped Followers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(arangodb_dropped_followers_count[15s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maintenance Runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(arangodb_maintenance_agency_sync_accum_runtime_msec{type=\"dbservers\"}[15s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(rate(arangodb_maintenance_phase1_accum_runtime_msec{type=\"dbservers\"}[15s]))",
     "legendFormat": "Phase1"
    },
    {
     "expr": "avg(rate(arangodb_maintenance_phase2_accum_runtime_msec{type=\"dbservers\"}[15s]))",
     "legendFormat": "Phase2"
    }
   ]
  },
  {
   "title": "Leader Shards",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "arangodb_shards_leader_count{type=\"dbservers\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SynchronizeShard Runtime",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_maintenance_action_runtime_msec_bucket{action=\"SynchronizeShard\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Supervision Runtime",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_agency_supervision_runtime_msec_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Shard Sync",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(arangodb_shards_not_replicated)",
     "legendFormat": "Not replicated"
    },
    {
     "expr": "sum(arangodb_shards_out_of_sync-arangodb_shards_not_replicated)",
     "legendFormat": "Partial Out of sync"
    }
   ]
  },
  {
   "title": "Agency Sync Time",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_maintenance_phase1_runtime_msec_bucket{type=\"dbservers\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CreateCollection Runtime",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_maintenance_action_runtime_msec_bucket{action=\"CreateCollection\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Maintenance Phase 1",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_maintenance_phase1_runtime_msec_bucket{type=\"dbservers\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Awake Worker Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(arangodb_scheduler_awake_threads)",
     "legendFormat": "Awake Workers"
    },
    {
     "expr": "sum(arangodb_scheduler_num_worker_threads-arangodb_scheduler_awake_threads)",
     "legendFormat": "Sleeping Workers"
    }
   ]
  },
  {
   "title": "AQL Execution Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(arangodb_aql_total_query_time_msec{type=\"dbservers\"}[1m]))",
     "legendFormat": "DBServers"
    },
    {
     "expr": "sum(rate(arangodb_aql_total_query_time_msec{type=\"coordinators\"}[1m]))",
     "legendFormat": "Coordinators"
    },
    {
     "expr": "sum(rate(arangodb_aql_total_query_time_msec{type=\"agents\"}[1m]))",
     "legendFormat": "Agents"
    },
    {
     "expr": "sum(rate(arangodb_aql_total_query_time_msec[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Accum Supervision Runtime Avg 30s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_agency_supervision_accum_runtime_msec[30s]))",
     "legendFormat": "Total time"
    },
    {
     "expr": "sum(increase(arangodb_agency_supervision_accum_runtime_wait_for_replication_msec[30s]))",
     "legendFormat": "Wait for replication"
    }
   ]
  },
  {
   "title": "Maintenance Phase 2",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_maintenance_phase2_runtime_msec_bucket{type=\"dbservers\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Scheduler Queue Length",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(arangodb_scheduler_queue_length) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "AQL Slow Queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_aql_slow_query[15s]))",
     "legendFormat": "Number of slow AQL queries"
    }
   ]
  },
  {
   "title": "Scheduler Queue Length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(arangodb_scheduler_queue_length)",
     "legendFormat": "Scheduler queue length"
    }
   ]
  },
  {
   "title": "AgencyComm Request Times",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(arangodb_agencycomm_request_time_msec_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "V8 Contexts Creation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_v8_context_created[15s]))",
     "legendFormat": "V8 contexts created"
    },
    {
     "expr": "sum(increase(arangodb_v8_context_destroyed[15s]))",
     "legendFormat": "V8 contexts destroyed"
    }
   ]
  },
  {
   "title": "V8 Contexts Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_v8_context_enter_failures[15s]))",
     "legendFormat": "V8 context acquisition failures"
    }
   ]
  },
  {
   "title": "Scheduler queue full errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_scheduler_queue_full_failures[15s]))",
     "legendFormat": "Scheduler queue full errors"
    }
   ]
  },
  {
   "title": "Agency Requests Total Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_agencycomm_request_time_msec_count{type=\"dbservers\"}[15s]))",
     "legendFormat": "DBServer"
    },
    {
     "expr": "sum(increase(arangodb_agencycomm_request_time_msec_count{type=\"coordinators\"}[20s]))",
     "legendFormat": "Coordinators"
    }
   ]
  }
 ]
}