{
 "title": "ArangoDB_3.8_for_dbadmins",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of drop-follower events",
     "type": "graph",
     "description": "Total number of drop-follower events. This metric is increased on leaders\nwhenever a write operation cannot be replicated to a follower during\nsynchronous replication, and it would be unsafe in terms of data consistency \nto keep that follower.\nThis metric was named `arangodb_dropped_followers_count` in previous\nversions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_dropped_followers_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of failed heartbeat transmissions",
     "type": "graph",
     "description": "Total number of failed heartbeat transmissions.\nServers in a cluster periodically send their heartbeats to\nthe agency to report their own liveliness. This counter gets\nincreased whenever sending such a heartbeat fails. In the single\nserver, this counter is only used in active failover mode.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_heartbeat_failures_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Time required to send a heartbeat",
     "type": "heatmap",
     "description": "Histogram of times required to send heartbeats. For every heartbeat\nsent the time is measured and an event is put into the histogram.\nIn the single server, this counter is only used in active failover mode.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_heartbeat_send_time_msec_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Time required to send a heartbeat (count of events per second)",
     "type": "graph",
     "description": "Histogram of times required to send heartbeats. For every heartbeat\nsent the time is measured and an event is put into the histogram.\nIn the single server, this counter is only used in active failover mode.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_heartbeat_send_time_msec_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Time required to send a heartbeat (average per second)",
     "type": "graph",
     "description": "Histogram of times required to send heartbeats. For every heartbeat\nsent the time is measured and an event is put into the histogram.\nIn the single server, this counter is only used in active failover mode.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_heartbeat_send_time_msec_sum[60s]) / rate(arangodb_heartbeat_send_time_msec_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of AQL queries finished",
     "type": "graph",
     "description": "Total number of AQL queries finished.\nThis metric was named `arangodb_aql_all_query` in previous\nversions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_aql_all_query_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Current number of AQL queries executing",
     "type": "graph",
     "description": "Current number of AQL queries executing.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "arangodb_aql_current_query", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Total memory limit for all AQL queries combined",
     "type": "graph",
     "description": "Total memory limit for all AQL queries combined, in bytes.\nIf this value is reported as `0`, it means there is no total memory\nlimit in place for AQL queries. The value can be adjusted by the setting\nthe `--query.global-memory-limit` startup option.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "arangodb_aql_global_memory_limit",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total memory usage of all AQL queries executing; granularity: 32768 bytes steps",
     "type": "graph",
     "description": "Total memory usage of all AQL queries currently executing.\nThe granularity of this metric is steps of 32768 bytes. The current\nmemory usage of all AQL queries will be compared against the configured\nlimit in the `--query.global-memory-limit` startup option. \nIf the startup option has a value of `0`, then no global memory limit\nwill be enforced. If the startup option has a non-zero value, queries\nwill be aborted once the total query memory usage goes above the configured\nlimit.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "arangodb_aql_global_memory_usage",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of times the global query memory limit threshold was reached",
     "type": "graph",
     "description": "Total number of times the global query memory limit threshold was reached.\nThis can happen if all running AQL queries in total try to use more memory than\nconfigured via the `--query.global-memory-limit` startup option.\nEvery time this counter will increase, an AQL query will have aborted with a \n\"resource limit exceeded\" error.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(arangodb_aql_global_query_memory_limit_reached_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of times a local query memory limit threshold was reached",
     "type": "graph",
     "description": "Total number of times a local query memory limit threshold was reached, i.e.\na single query tried to allocate more memory than configured in the query's\n`memoryLimit` attribute or the value configured via the startup option\n`--query.memory-limit`.\nEvery time this counter will increase, an AQL query will have aborted with a \n\"resource limit exceeded\" error.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "rate(arangodb_aql_local_query_memory_limit_reached_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Execution time histogram for all AQL queries",
     "type": "heatmap",
     "description": "Execution time histogram for all AQL queries, in seconds.\nThe histogram includes all slow queries.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_aql_query_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Execution time histogram for all AQL queries (count of events per second)",
     "type": "graph",
     "description": "Execution time histogram for all AQL queries, in seconds.\nThe histogram includes all slow queries.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(arangodb_aql_query_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Execution time histogram for all AQL queries (average per second)",
     "type": "graph",
     "description": "Execution time histogram for all AQL queries, in seconds.\nThe histogram includes all slow queries.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(arangodb_aql_query_time_sum[60s]) / rate(arangodb_aql_query_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Execution time histogram for slow AQL queries",
     "type": "heatmap",
     "description": "Execution time histogram for slow AQL queries, in seconds.\nQueries are considered \"slow\" if their execution time is above the\nthreshold configured in the startup options `--query.slow-threshold`\nor `--query.slow-streaming-threshold`, resp.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_aql_slow_query_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Execution time histogram for slow AQL queries (count of events per second)",
     "type": "graph",
     "description": "Execution time histogram for slow AQL queries, in seconds.\nQueries are considered \"slow\" if their execution time is above the\nthreshold configured in the startup options `--query.slow-threshold`\nor `--query.slow-streaming-threshold`, resp.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(arangodb_aql_slow_query_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Execution time histogram for slow AQL queries (average per second)",
     "type": "graph",
     "description": "Execution time histogram for slow AQL queries, in seconds.\nQueries are considered \"slow\" if their execution time is above the\nthreshold configured in the startup options `--query.slow-threshold`\nor `--query.slow-streaming-threshold`, resp.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "rate(arangodb_aql_slow_query_time_sum[60s]) / rate(arangodb_aql_slow_query_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total execution time of all AQL queries",
     "type": "graph",
     "description": "Total execution time of all AQL queries, in milliseconds,\nincluding all slow queries.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(arangodb_aql_total_query_time_msec_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in collection truncate operations (count of events per second)",
     "type": "graph",
     "description": "Total time spent in collection truncate operations, including both\nuser-initiated truncate operations and truncate operations\nexecuted by the synchronous replication on followers.\nNote that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "rate(arangodb_collection_truncate_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total time spent in collection truncate operations",
     "type": "heatmap",
     "description": "Total time spent in collection truncate operations, including both\nuser-initiated truncate operations and truncate operations\nexecuted by the synchronous replication on followers.\nNote that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_collection_truncate_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Total number of collection truncate operations (excl. synchronous replication)",
     "type": "graph",
     "description": "Total number of collection truncate operations on leaders (excl. synchronous\nreplication). Note that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(arangodb_collection_truncates_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in collection truncate operations (average per second)",
     "type": "graph",
     "description": "Total time spent in collection truncate operations, including both\nuser-initiated truncate operations and truncate operations\nexecuted by the synchronous replication on followers.\nNote that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(arangodb_collection_truncate_time_sum[60s]) / rate(arangodb_collection_truncate_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document insert operations (count of events per second)",
     "type": "graph",
     "description": "Total time spent in document insert operations, including both\nuser-initiated insert operations and insert operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rate(arangodb_document_insert_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document insert operations",
     "type": "heatmap",
     "description": "Total time spent in document insert operations, including both\nuser-initiated insert operations and insert operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_insert_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Total time spent in document read-by-primary-key operations",
     "type": "heatmap",
     "description": "Total time spent in document read-by-primary-key operations. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_read_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Total time spent in document insert operations (average per second)",
     "type": "graph",
     "description": "Total time spent in document insert operations, including both\nuser-initiated insert operations and insert operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(arangodb_document_insert_time_sum[60s]) / rate(arangodb_document_insert_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document read-by-primary-key operations (average per second)",
     "type": "graph",
     "description": "Total time spent in document read-by-primary-key operations. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "rate(arangodb_document_read_time_sum[60s]) / rate(arangodb_document_read_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document read-by-primary-key operations (count of events per second)",
     "type": "graph",
     "description": "Total time spent in document read-by-primary-key operations. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(arangodb_document_read_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document remove operations (count of events per second)",
     "type": "graph",
     "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "rate(arangodb_document_remove_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document remove operations",
     "type": "heatmap",
     "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_remove_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Total time spent in document replace operations",
     "type": "heatmap",
     "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_replace_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Total time spent in document remove operations (average per second)",
     "type": "graph",
     "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(arangodb_document_remove_time_sum[60s]) / rate(arangodb_document_remove_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document replace operations (average per second)",
     "type": "graph",
     "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "rate(arangodb_document_replace_time_sum[60s]) / rate(arangodb_document_replace_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document replace operations (count of events per second)",
     "type": "graph",
     "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "rate(arangodb_document_replace_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document update operations (count of events per second)",
     "type": "graph",
     "description": "Total time spent in document update operations, including both\nuser-initiated update operations and update operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "rate(arangodb_document_update_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document update operations",
     "type": "heatmap",
     "description": "Total time spent in document update operations, including both\nuser-initiated update operations and update operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_update_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Number of transactions aborted",
     "type": "graph",
     "description": "Total number of transactions aborted. In the cluster, this metric will \nbe collected separately for transactions on coordinators and the\ntransaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_aborted` in previous\nversions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "rate(arangodb_transactions_aborted_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time spent in document update operations (average per second)",
     "type": "graph",
     "description": "Total time spent in document update operations, including both\nuser-initiated update operations and update operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "rate(arangodb_document_update_time_sum[60s]) / rate(arangodb_document_update_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of expired transactions",
     "type": "graph",
     "description": "Total number of expired transactions, i.e. transactions that have\nbeen begun but that were automatically garbage-collected due to \ninactivity within the transactions' time-to-live (TTL) period.\nIn the cluster, this metric will be collected separately for transactions \non coordinators and the transaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_expired` in previous\nversions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "rate(arangodb_transactions_expired_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of transactions committed",
     "type": "graph",
     "description": "Total number of transactions committed. In the cluster, this metric will \nbe collected separately for transactions on coordinators and the\ntransaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_committed` in previous\nversions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "rate(arangodb_transactions_committed_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Bytes received for a request (count of events per second)",
     "type": "graph",
     "description": "Histogram of the received request sizes in bytes.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_bytes_received_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of transactions started",
     "type": "graph",
     "description": "Total number of transactions started/begun. In the cluster, this metric will \nbe collected separately for transactions on coordinators and the\ntransaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_started` in previous\nversions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "rate(arangodb_transactions_started_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Bytes sent for a request",
     "type": "heatmap",
     "description": "Histogram of the sent response sizes in bytes\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_bytes_sent_bucket[60s])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes received for a request",
     "type": "heatmap",
     "description": "Histogram of the received request sizes in bytes.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_bytes_received_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Bytes sent for a request (average per second)",
     "type": "graph",
     "description": "Histogram of the sent response sizes in bytes\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_bytes_sent_sum[60s]) / rate(arangodb_client_connection_statistics_bytes_sent_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Bytes received for a request (average per second)",
     "type": "graph",
     "description": "Histogram of the received request sizes in bytes.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_bytes_received_sum[60s]) / rate(arangodb_client_connection_statistics_bytes_received_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "I/O time needed to answer a request",
     "type": "heatmap",
     "description": "Histogram of I/O times needed to answer a request. This includes the time\nrequired to read the incoming request as well as the time required to send\nthe response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_io_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Bytes sent for a request (count of events per second)",
     "type": "graph",
     "description": "Histogram of the sent response sizes in bytes\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_bytes_sent_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "I/O time needed to answer a request (average per second)",
     "type": "graph",
     "description": "Histogram of I/O times needed to answer a request. This includes the time\nrequired to read the incoming request as well as the time required to send\nthe response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_io_time_sum[60s]) / rate(arangodb_client_connection_statistics_io_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "The number of client connections that are currently open",
     "type": "graph",
     "description": "The number of client connections that are currently open.\nNote: this metric considers only HTTP and HTTP/2 connections, but not VST\nconnections.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "arangodb_client_connection_statistics_client_connections",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Queueing time needed for requests (count of events per second)",
     "type": "graph",
     "description": "Histogram of the time requests are spending on a queue waiting to be\nprocessed. The overwhelming majority of these times should be clearly\nsub-second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_queue_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "I/O time needed to answer a request (count of events per second)",
     "type": "graph",
     "description": "Histogram of I/O times needed to answer a request. This includes the time\nrequired to read the incoming request as well as the time required to send\nthe response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_io_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Request time needed to answer a request",
     "type": "heatmap",
     "description": "Histogram of the time required to actually process a request. This does not\ninclude the time required to read the incoming request, the time the request\nis sitting on the queue, or the time required to send the response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_request_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Queueing time needed for requests",
     "type": "heatmap",
     "description": "Histogram of the time requests are spending on a queue waiting to be\nprocessed. The overwhelming majority of these times should be clearly\nsub-second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_queue_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Request time needed to answer a request (average per second)",
     "type": "graph",
     "description": "Histogram of the time required to actually process a request. This does not\ninclude the time required to read the incoming request, the time the request\nis sitting on the queue, or the time required to send the response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_request_time_sum[60s]) / rate(arangodb_client_connection_statistics_request_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Queueing time needed for requests (average per second)",
     "type": "graph",
     "description": "Histogram of the time requests are spending on a queue waiting to be\nprocessed. The overwhelming majority of these times should be clearly\nsub-second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_queue_time_sum[60s]) / rate(arangodb_client_connection_statistics_queue_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time needed to answer a request (count of events per second)",
     "type": "graph",
     "description": "Histogram of the total times required to process a request. This includes\nthe time required to read the incoming request, the time the request is\nsitting in the queue, the time to actually process the request, and the\ntime required to send the response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_total_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Request time needed to answer a request (count of events per second)",
     "type": "graph",
     "description": "Histogram of the time required to actually process a request. This does not\ninclude the time required to read the incoming request, the time the request\nis sitting on the queue, or the time required to send the response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_request_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of asynchronously executed HTTP requests",
     "type": "graph",
     "description": "This counter reflects the total number of **asynchronous** HTTP (or VST)\nrequests which have hit this particular instance of `arangod`. Asynchronous\nrefers to the fact that the response is not sent with the HTTP response,\nbut is rather queried separately using the `/_api/jobs` API.\nSee [this Section](async-results-management.html) for details.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_async_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time needed to answer a request",
     "type": "heatmap",
     "description": "Histogram of the total times required to process a request. This includes\nthe time required to read the incoming request, the time the request is\nsitting in the queue, the time to actually process the request, and the\ntime required to send the response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_total_time_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Number of HTTP GET requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **GET** \nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_http_get_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time needed to answer a request (average per second)",
     "type": "graph",
     "description": "Histogram of the total times required to process a request. This includes\nthe time required to read the incoming request, the time the request is\nsitting in the queue, the time to actually process the request, and the\ntime required to send the response.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "rate(arangodb_client_connection_statistics_total_time_sum[60s]) / rate(arangodb_client_connection_statistics_total_time_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of HTTP OPTIONS requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **OPTIONS** \nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_http_options_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of HTTP DELETE requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **DELETE** \nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_http_delete_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of HTTP POST requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **POST** \nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_http_post_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of HTTP HEAD requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **HEAD** \nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_http_head_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of other HTTP requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **other**\nor **ILLEGAL** requests which have hit this particular instance of\n`arangod`. These are all requests, which are not one of the following:\n`DELETE`, `GET`, `HEAD`, `POST`, `PUT`, `OPTIONS`, `PATCH`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_other_http_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of HTTP PATCH requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **PATCH** \nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_http_patch_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of HTTP requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) requests which\nhave hit this particular instance of `arangod`. Note that this counter\nis ever growing during the lifetime of the `arangod` process. However,\nwhen the process is restarted, it starts from scratch. In the Grafana\ndashboards, it is usually visualized as a rate per second, averaged\nwith a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_total_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of HTTP PUT requests",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) **PUT** \nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_http_put_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of intermediate commits performed in transactions",
     "type": "graph",
     "description": "Number of intermediate commits performed in transactions.\nAn intermediate commit happens if a logical transaction needs to be\nsplit into multiple physical transaction because of the volume of data\nhandled in the transaction. The thresholds for when to perform an\nintermediate commit can be controlled by startup options \n`--rocksdb.intermediate-commit-count` (number of write operations after\nwhich an intermediate commit is triggered) and `--rocksdb.intermediate-commit-size`\n(cumulated size of write operations after which an intermediate commit is triggered).\nThe values can also be overridden for individual transactions.\nThis metric was named `arangodb_intermediate_commits` in previous\nversions of ArangoDb.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "rate(arangodb_intermediate_commits_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of HTTP requests executed by superuser/JWT",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST)\nrequests that have been authenticated with the JWT superuser token,\nwhich have hit this particular instance of\n`arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_superuser_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of minor page faults",
     "type": "graph",
     "description": "The number of minor faults the process has made which have not required\nloading a memory page from disk. This figure is not reported on Windows.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "expr": "arangodb_process_statistics_minor_page_faults_total",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of HTTP requests executed by user clients",
     "type": "graph",
     "description": "This counter reflects the total number of HTTP (or VST) requests\nthat have been authenticated for some user (as opposed to with the\nJWT superuser token), which have hit this particular instance of\n`arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "rate(arangodb_http_request_statistics_user_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Resident set size",
     "type": "graph",
     "description": "The total size of the number of pages the process has in real memory.\nThis is just the pages which count toward text, data, or stack space.\nThis does not include pages which have not been demand-loaded in, or\nwhich are swapped out. The resident set size is reported in bytes.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "targets": [
      {
       "expr": "arangodb_process_statistics_resident_set_size",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of major page faults",
     "type": "graph",
     "description": "On Windows, this figure contains the total number of page faults.\nOn other system, this figure contains the number of major faults the\nprocess has made which have required loading a memory page from disk.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "rate(arangodb_process_statistics_major_page_faults_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Process system time",
     "type": "graph",
     "description": "Amount of time that this process has been scheduled in kernel mode,\nmeasured in seconds.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "targets": [
      {
       "expr": "arangodb_process_statistics_system_time",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of threads",
     "type": "graph",
     "description": "Number of threads in the arangod process.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "arangodb_process_statistics_number_of_threads",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Virtual memory size",
     "type": "graph",
     "description": "On Windows, this figure contains the total amount of memory that the\nmemory manager has committed for the arangod process. On other systems,\nthis figure contains the size of the virtual memory the process is\nusing.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "targets": [
      {
       "expr": "arangodb_process_statistics_virtual_memory_size",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Resident set size as fraction of system memory",
     "type": "graph",
     "description": "The relative size of the number of pages the process has in real\nmemory compared to system memory. This is just the pages which count\ntoward text, data, or stack space. This does not include pages which\nhave not been demand-loaded in, or which are swapped out. The value is a\nratio between 0.00 and 1.00.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "arangodb_process_statistics_resident_set_size_percent",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Percentage of time that the system CPUs have been idle",
     "type": "graph",
     "description": "Percentage of time that the system CPUs have been idle, as \na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "targets": [
      {
       "expr": "arangodb_server_statistics_idle_percent",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Process user time",
     "type": "graph",
     "description": "Amount of time that this process has been scheduled in user mode,\nmeasured in seconds.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "arangodb_process_statistics_user_time",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Physical memory in bytes",
     "type": "graph",
     "description": "Physical memory of the system in bytes, as reported by the operating system \nunless the environment variable `ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY` \nis set. In that case, the environment variable's value will be reported.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "targets": [
      {
       "expr": "arangodb_server_statistics_physical_memory",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of CPU cores visible to the arangod process",
     "type": "graph",
     "description": "Number of CPU cores visible to the arangod process, unless the\nenvironment variable `ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES`\nis set. In that case, the environment variable's value will be reported.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "targets": [
      {
       "expr": "arangodb_server_statistics_cpu_cores",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Percentage of time that the system CPUs have spent in kernel mode",
     "type": "graph",
     "description": "Percentage of time that the system CPUs have spent in kernel mode, as\na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "targets": [
      {
       "expr": "arangodb_server_statistics_system_percent",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Percentage of time that the system CPUs have been waiting for I/O",
     "type": "graph",
     "description": "Percentage of time that the system CPUs have been waiting for I/O, as\na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "targets": [
      {
       "expr": "arangodb_server_statistics_iowait_percent",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of V8 contexts currently alive",
     "type": "graph",
     "description": "Number of V8 contexts currently alive. Normally, only coordinators and\nsingle servers should have V8 contexts, for dbservers and agents the\nvalue is always zero.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "targets": [
      { "expr": "arangodb_v8_context_alive", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Number of seconds elapsed since server start",
     "type": "graph",
     "description": "Number of seconds elapsed since server start, including fractional\nseconds.\nThis metric was named `arangodb_server_statistics_server_uptime`\nin previous versions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
     "targets": [
      {
       "expr": "rate(arangodb_server_statistics_server_uptime_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of V8 contexts currently dirty",
     "type": "graph",
     "description": "This gauge reflects the number of V8 contexts that are currently dirty.\nA V8 context is dirty, if it has executed JavaScript for some time and\nis due for a garbage collection.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
     "targets": [
      { "expr": "arangodb_v8_context_dirty", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Percentage of time that the system CPUs have spent in user mode",
     "type": "graph",
     "description": "Percentage of time that the system CPUs have spent in user mode, as\na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
     "targets": [
      {
       "expr": "arangodb_server_statistics_user_percent",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Maximum number of concurrent V8 contexts",
     "type": "graph",
     "description": "This is the maximum number of concurrent V8 contexts. This is limited\nby a server option, since V8 contexts can use a lot of RAM. V8 contexts\nare created and destroyed as needed up to the limit shown in this metric.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
     "targets": [
      { "expr": "arangodb_v8_context_max", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Number of V8 contexts currently busy",
     "type": "graph",
     "description": "Number of V8 contexts currently busy, that means, they are currently\nworking on some JavaScript task. Normally, only coordinators and\nsingle servers should have V8 contexts, for dbservers and agents the\nvalue is always zero.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
     "targets": [
      { "expr": "arangodb_v8_context_busy", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Total number of document write operations by synchronous replication",
     "type": "graph",
     "description": "Total number of document write operations by synchronous replication.\nThis metric is only present if the option\n`--server.export-read-write-metrics` is set to `true`.\nTotal number of document write operations (insert, update, replace, remove)\nexecuted by the synchronous replication on followers.\nThis metric is only present if the option `--server.export-read-write-metrics` \nis set to `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
     "targets": [
      {
       "expr": "rate(arangodb_document_writes_replication_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of V8 contexts currently free",
     "type": "graph",
     "description": "This gauge reflects the number of V8 contexts that are currently free.\nIf this number drops to 0 there might be a shortage of V8 contexts.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
     "targets": [
      { "expr": "arangodb_v8_context_free", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "(DC-2-DC only) Number of times the database and collection overviews have been requested",
     "type": "graph",
     "description": "When using a DC-2-DC configuration of ArangoDB this metric is active on both data-centers.\nIt indicates that the follower data-center periodically matches the available databases and collections\nin order to mirror them. If no DC-2-DC is set up this value is expected to be 0.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_cluster_inventory_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Minimum number of concurrent V8 contexts",
     "type": "graph",
     "description": "This is the minimum number of concurrent V8 contexts. This is limited\nby a server option. V8 contexts are created and destroyed as needed\nbut there are never fewer than the limit shown in this metric.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "targets": [
      { "expr": "arangodb_v8_context_min", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Total number of bytes replicated in initial asynchronous phase",
     "type": "graph",
     "description": "During initial replication the existing data from the leader is copied asynchronously\nover to new shards. The amount of requests required to transport data to this server,\nas a replica for a shard, is counted here.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_dump_bytes_received_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of collection truncate operations by synchronous replication",
     "type": "graph",
     "description": "Total number of collection truncate operations by synchronous\nreplication on followers. Note that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(arangodb_collection_truncates_replication_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated wait time for replication requests in initial asynchronous phase",
     "type": "graph",
     "description": "During initial replication the existing data from the leader is copied asynchronously\nover to new shards. The accumulated time the follower waited for the leader to send\nthe data is counted here.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_dump_request_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of refusal answers from a follower during synchronous replication",
     "type": "graph",
     "description": "Number of refusal answers from a follower during synchronous replication.\nA refusal answer will only be sent by a follower if the follower is under\nthe impression that the replication request was not sent by the current\nshard leader. This can happen if replication requests to the follower are \ndelayed or the follower is slow to process incoming requests and there was \na leader change for the shard.\nIf such a refusal answer is received by the shard leader, it will drop the\nfollower from the list of followers.\nThis metrics was named `arangodb_refused_followers_count` in previous\nversions of ArangoDB.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(arangodb_refused_followers_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of failed connection attempts and response errors during initial asynchronous replication",
     "type": "graph",
     "description": "During initial replication the existing data from the leader is copied asynchronously\nover to new shards. Whenever there is a communication issue between the follower and\nthe leader of the shard it will be counted here for the follower. This communication\nissues cover failed connections or http errors, but they also cover invalid or\nunexpected data formats revieved on the follower.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_failed_connects_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated time needed to apply asynchronously replicated data on initial synchronization of shards",
     "type": "graph",
     "description": "Measures the time required to clone the existing leader copy of the data onto a new replica shard.\nWill only be measured on the follower server. This time is expected to increase whenever new followers\nare created, e.g. increasing replication factor, shard redistribution.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_dump_apply_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated time needed to request replication docs data",
     "type": "graph",
     "description": "This counter exhibits the accumulated wait time for requesting actual\ndocuments for the initial replication, in milliseconds. This is part\nof the older (pre 3.8) initial replication protocol, which might\nstill be used in 3.8 for collections which have been created by older\nversions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the time used for the final step of actually\ngetting the needed documents.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_docs_requests_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of documents replicated in initial asynchronous phase",
     "type": "graph",
     "description": "During initial replication the existing data from the leader is copied asynchronously\nover to new shards. The amount of documents transported to this server, as a replica for\na shard, is counted here.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_dump_documents_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated wait time for replication keys requests",
     "type": "graph",
     "description": "This counter exhibits the accumulated wait time for fetching key\nlists for a chunk, in milliseconds. This is part of the\nolder (pre 3.8) initial replication protocol, which might still be used\nin 3.8 for collections which have been created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the time used for the second step of getting\nlists of key/revision pairs for each chunk.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_keys_requests_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of requests used in initial asynchronous replication phase",
     "type": "graph",
     "description": "During initial replication the existing data from the leader is copied asynchronously\nover to new shards. The amount of data transported to this server, as a replica for\na shard, is counted here.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_dump_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated amount of bytes received in initial sync",
     "type": "graph",
     "description": "This counter exhibits the accumulated number of bytes received\nfor initial synchronization of shards. This is part of the\nolder (pre 3.8) initial replication protocol, which might still be used\nin 3.8 for collections which have been created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates number of bytes received for all three steps.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_sync_bytes_received_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated wait time for replication key chunks determination requests",
     "type": "graph",
     "description": "This counter exhibits the accumulated wait time for replication key\nchunks determination requests, in milliseconds. This is part of the\nolder (pre 3.8) initial replication protocol, which might still be used\nin 3.8 for collections which have been created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the time used for the initial step of getting\nthe checksums for the key chunks.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_chunks_requests_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of documents removed by replication initial sync",
     "type": "graph",
     "description": "This counter exhibits the total number of documents removed on the\nfollower during initial synchronization of shards. This is part of the\nolder (pre 3.8) initial replication protocol, which might still be\nused in 3.8 for collections which have been created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the total number of documents removed in the\nthird step.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_sync_docs_removed_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated time needed to apply replication initial sync insertions",
     "type": "graph",
     "description": "Accumulated time needed to apply replication initial sync insertions.\nThis counter exhibits the accumulated wait time for actually inserting\ndocuments for the initial synchronization, in milliseconds. This is\npart of the older (pre 3.8) initial replication protocol, which might\nstill be used in 3.8 for collections which have been created by older\nversions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the time used for the actual insertion of\nreplicated documents on the follower.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_insert_apply_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of replication initial sync docs requests",
     "type": "graph",
     "description": "This counter exhibits the total number of times documents have been\nfetched on the follower from the leader during initial synchronization\nof shards. This is part of the older (pre 3.8) initial replication\nprotocol, which might still be used in 3.8 for collections which have\nbeen created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the total number of times documents have been\nfetched from the leader in the third step.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_sync_docs_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated time needed to apply replication initial sync removals",
     "type": "graph",
     "description": "This counter exhibits the accumulated wait time for removing local\ndocuments during initial synchronization of a shard on the follower,\nin milliseconds. This is part of the older (pre 3.8) initial\nreplication protocol, which might still be used in 3.8 for collections\nwhich have been created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the time used for the intermediate step of\nremoving unneeded documents on the follower.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_remove_apply_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of synchronous replication requests",
     "type": "graph",
     "description": "The total amount of all synchronous replication operation requests\nbetween dbservers being done.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_synchronous_requests_total_number_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of documents inserted by replication initial sync",
     "type": "graph",
     "description": "This counter exhibits the total number of documents inserted on the\nfollower during initial synchronization of shards. This is part of the\nolder (pre 3.8) initial replication protocol, which might still be\nused in 3.8 for collections which have been created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the total number of documents inserted in the\nthird step.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_sync_docs_inserted_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated time needed to apply replication tailing data",
     "type": "graph",
     "description": "The accumulated time needed to locally process the continuous\nreplication log on a follower received from a replication\nleader.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_apply_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of documents requested by replication initial sync",
     "type": "graph",
     "description": "This counter exhibits the total number of documents fetched on the\nfollower from the leader during initial synchronization of shards.\nThis is part of the older (pre 3.8) initial replication protocol,\nwhich might still be used in 3.8 for collections which have been\ncreated by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric accumulates the total number of documents fetched from the\nleader in the third step.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_sync_docs_requested_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated number of replication tailing document inserts/replaces processed",
     "type": "graph",
     "description": "The accumulated number of replication tailing document inserts/replaces processed on a follower.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_documents_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of replication initial sync keys requests",
     "type": "graph",
     "description": "This counter exhibits the accumulated number of keys requests for\ninitial synchronization of shards. This is part of the\nolder (pre 3.8) initial replication protocol, which might still be used\nin 3.8 for collections which have been created by older versions.\n\nIn this older protocol, the follower first fetches an overview over\na shard from the leader. This does a full collection scan and\ndivides the primary keys in the collection into equal sized chunks.\nThen, a checksum for each chunk is returned. The same is then done\non the follower and the checksums are compared, chunk by chunk. For\neach chunk, for which the checksums do not match, the list of keys and\nrevisions is fetched from the leader. This then enables the follower\nto fetch the actually needed documents and remove superfluous ones\nlocally.\n\nThis metric counts the number of times the follower fetches a list of\nkeys for some chunk.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_initial_sync_keys_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of replication tailing markers processed",
     "type": "graph",
     "description": "The number of replication tailing markers processed on a follower\ndbserver. Markers are specific operations which are part of the\nwrite-ahead log (WAL). Example actions which are being used in\nmarkers: Create or drop a database. Create, drop, rename, change\nor truncate a collection. Create or drop an index. Create, drop,\nchange a view. Start, commit or abort a transaction.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_markers_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total time needed for all synchronous replication requests",
     "type": "graph",
     "description": "The total time needed for all synchronous replication requests\nbetween dbservers being done.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_synchronous_requests_total_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Aggregated wait time for replication tailing requests",
     "type": "graph",
     "description": "Aggregated wait time for replication tailing requests.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_request_time_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated number of bytes received for replication tailing requests",
     "type": "graph",
     "description": "The accumulated number of bytes received from a leader for replication tailing requests. The higher the amount of bytes is, the more data is being processed afterwards on the follower dbserver.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_bytes_received_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of leader shards on this machine",
     "type": "graph",
     "description": "Number of leader shards on this machine. Every shard has a leader and\npotentially multiple followers.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "targets": [
      { "expr": "arangodb_shards_leader_number", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Number of replication tailing failures due to missing tick on leader",
     "type": "graph",
     "description": "The number of replication tailing failures due to missing tick on leader.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_follow_tick_failures_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of shards on this machine",
     "type": "graph",
     "description": "Number of shards on this machine. Every shard has a leader and\npotentially multiple followers. This metric counts both leader and\nfollower shards.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "targets": [
      { "expr": "arangodb_shards_number", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Number of replication tailing document removals processed",
     "type": "graph",
     "description": "The amount of document removal based marker operations on a\nfollower dbserver.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_removals_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of times a mismatching shard checksum was detected when syncing shards",
     "type": "graph",
     "description": "Number of times a mismatching shard checksum was detected when\nsyncing shards. This is a very special metric which is rarely used.\nWhen followers of shards get in sync with their leaders, just when\neverything is completed a final checksum is taken as an additional\nprecaution. If this checksum differs between leader an follower, the\nresync process starts from scratch.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "expr": "rate(arangodb_sync_wrong_checksum_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of replication tailing requests",
     "type": "graph",
     "description": "The total amount of network replication tailing requests.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "rate(arangodb_replication_tailing_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Request time for Agency requests (count of events per second)",
     "type": "graph",
     "description": "This histogram shows how long requests to the agency took.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "targets": [
      {
       "expr": "rate(arangodb_agencycomm_request_time_msec_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of shards not replicated at all",
     "type": "graph",
     "description": "Number of shards not replicated at all. This is counted for all shards\nfor which this server is currently the leader. The number is increased\nby one for every shards for which no follower is in sync.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "targets": [
      { "expr": "arangodb_shards_not_replicated", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    },
    {
     "title": "Number of leader shards not fully replicated",
     "type": "graph",
     "description": "Number of leader shards not fully replicated. This is counted for all\nshards for which this server is currently the leader. The number is\nincreased by one for every shards for which not all followers are in sync.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "targets": [
      { "expr": "arangodb_shards_out_of_sync", "legendFormat": "{{instance}}:{{shortname}}" }
     ]
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of times RocksDB has entered a stalled (slowed) write state",
     "type": "graph",
     "description": "This counter reflects the number of times RocksDB was observed by\nArangoDB to have entered a stalled (slowed) write state.\n\nIf the RocksDB background threads which do cleanup and compaction\ncannot keep up with the writing, then RocksDB first throttles its\nwrite rate (\"write stall\") and later stops the writing entirely\n(\"write stop\"). Both are suboptimal, since the write rate is too high.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(arangodb_rocksdb_write_stalls_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of times RocksDB has entered a stopped write state",
     "type": "graph",
     "description": "This counter reflects the number of times RocksDB was observed by\nArangoDB to have entered a stopped write state.\n\nIf the RocksDB background threads which do cleanup and compaction\ncannot keep up with the writing, then RocksDB first throttles its\nwrite rate (\"write stall\") and later stops the writing entirely\n(\"write stop\"). Both are suboptimal, since the write rate is too high,\nbut write stops are considerably worse, since they can lead to service\nunavailability.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "rate(arangodb_rocksdb_write_stops_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time to lease a connection from the connection pool",
     "type": "heatmap",
     "description": "Time to lease a connection from the connection pool. There are two pools,\none for the agency communication with label `AgencyComm` and one for\nthe other cluster internal communication with label `ClusterComm`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_connection_pool_lease_time_hist_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Time to lease a connection from the connection pool (count of events per second)",
     "type": "graph",
     "description": "Time to lease a connection from the connection pool. There are two pools,\none for the agency communication with label `AgencyComm` and one for\nthe other cluster internal communication with label `ClusterComm`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_connection_pool_lease_time_hist_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Time to lease a connection from the connection pool (average per second)",
     "type": "graph",
     "description": "Time to lease a connection from the connection pool. There are two pools,\none for the agency communication with label `AgencyComm` and one for\nthe other cluster internal communication with label `ClusterComm`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_connection_pool_lease_time_hist_sum[60s]) / rate(arangodb_connection_pool_lease_time_hist_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of requests forwarded to another coordinator",
     "type": "graph",
     "description": "Number of requests forwarded to another coordinator.\nRequest forwarding can happen in load-balanced setups,\nwhen one coordinator receives and forwards requests \nthat can only be handled by a different coordinator.\nThis includes requests for streaming transactions,\nAQL, query cursors, Pregel jobs and some others.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(arangodb_network_forwarded_requests_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request time for Agency requests",
     "type": "heatmap",
     "description": "This histogram shows how long requests to the agency took.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(arangodb_agencycomm_request_time_msec_bucket[60s])) by (le))"
      }
     ]
    },
    {
     "title": "Number of outgoing internal requests in flight",
     "type": "graph",
     "description": "Number of outgoing internal requests in flight. This metric is increased\nwhenever any cluster-internal request is about to be sent via the underlying \nconnection pool, and is decreased whenever a response for such a request is\nreceived or the request runs into a timeout.\nThis metric provides an estimate of the fan-out of operations. For example,\na user operation on a collection with a single shard will normally lead to\na single internal request (plus replication), whereas an operation on a\ncollection with 10 shards may lead to a fan-out of 10 (plus replication).\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "arangodb_network_requests_in_flight",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Request time for Agency requests (average per second)",
     "type": "graph",
     "description": "This histogram shows how long requests to the agency took.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(arangodb_agencycomm_request_time_msec_sum[60s]) / rate(arangodb_agencycomm_request_time_msec_count[60s])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of V8 context enter failures",
     "type": "graph",
     "description": "Total number of V8 context enter failures. A context receives a context\nenter event every time it begins to execute some JavaScript. If no\ncontext is available at such a time the system waits for 60s for a\ncontext to become free. If this does not happen within the 60s, the\ncontext enter event fails, a warning is logged and this counter is\nincreased by one.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "rate(arangodb_v8_context_enter_failures_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Number of internal requests that have timed out",
     "type": "graph",
     "description": "Number of internal requests that have timed out. This metric is increased\nwhenever any cluster-internal request executed in the underlying connection\npool runs into a timeout.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rate(arangodb_network_request_timeouts_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of V8 context exit events",
     "type": "graph",
     "description": "This counter reflects the total number of V8 context exit events.\nA context receives a context exit event every time it finishes to\nexecute some JavaScript.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rate(arangodb_v8_context_exited_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "V8",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of V8 contexts ever created",
     "type": "graph",
     "description": "This counter reflects the total number of V8 contexts ever created. It is\nOK if this number keeps growing since the V8 contexts are created and\ndestroyed as needed. In rare cases a high fluctuation can indicate\nsome unfortunate usage pattern.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(arangodb_v8_context_created_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Accumulated total time for creating V8 contexts",
     "type": "graph",
     "description": "This counter reflects the accumulated total time for creating V8\ncontexts, in milliseconds. It is OK if this number keeps growing since\nthe V8 contexts are created and destroyed as needed. In rare cases a\nhigh fluctuation can indicate some unfortunate usage pattern.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(arangodb_v8_context_creation_time_msec_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of V8 contexts ever destroyed",
     "type": "graph",
     "description": "This counter reflects the total number of V8 contexts ever destroyed.\nIt is OK if this number keeps growing since the V8 contexts are\ncreated and destroyed as needed. In rare cases a high fluctuation can\nindicate some unfortunate usage pattern.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(arangodb_v8_context_destroyed_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    },
    {
     "title": "Total number of V8 context enter events",
     "type": "graph",
     "description": "Total number of V8 context enter events. A context receives a context\nenter event every time it begins to execute some JavaScript. This number\nis a rough estimate as to how much JavaScript the server executes.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(arangodb_v8_context_entered_total[3m])",
       "legendFormat": "{{instance}}:{{shortname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Agency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  }
 ]
}