{
 "title": "ArangoDB_3.9_for_appdevelopers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of drop-follower events",
   "type": "graph",
   "description": "Total number of drop-follower events. This metric is increased on leaders\nwhenever a write operation cannot be replicated to a follower during\nsynchronous replication, and it would be unsafe in terms of data consistency\nto keep that follower.\nThis metric was named `arangodb_dropped_followers_count` in previous\nversions of ArangoDB.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_dropped_followers_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of failed heartbeat transmissions",
   "type": "graph",
   "description": "Total number of failed heartbeat transmissions.\nServers in a cluster periodically send their heartbeats to\nthe Agency to report their own liveliness. This counter gets\nincreased whenever sending such a heartbeat fails. In the single\nserver, this counter is only used in active failover mode.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_heartbeat_failures_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Time required to send a heartbeat",
   "type": "heatmap",
   "description": "Histogram of times required to send heartbeats. For every heartbeat\nsent the time is measured and an event is put into the histogram.\nIn the single server, this counter is only used in active failover mode.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_heartbeat_send_time_msec_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Time required to send a heartbeat (count of events per second)",
   "type": "graph",
   "description": "Histogram of times required to send heartbeats. For every heartbeat\nsent the time is measured and an event is put into the histogram.\nIn the single server, this counter is only used in active failover mode.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_heartbeat_send_time_msec_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Time required to send a heartbeat (average per second)",
   "type": "graph",
   "description": "Histogram of times required to send heartbeats. For every heartbeat\nsent the time is measured and an event is put into the histogram.\nIn the single server, this counter is only used in active failover mode.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_heartbeat_send_time_msec_sum[3m]) / rate(arangodb_heartbeat_send_time_msec_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of delays in the io heartbeat test",
   "type": "graph",
   "description": "This counter is increased whenever the io heartbeat encounters a delay\nof at least 1s when writing a small file to the database directory,\nreading it and then removing it again.\nThis test is done periodically to ensure that the underlying volume is\nusable and performs reasonably well. The test can be switched off\nexplicitly with the flag `--database.io-heartbeat=false`, but the\ndefault is `true`. Furthermore, every such failure leads to a line in\nthe log at INFO level for the `ENGINES` topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_ioheartbeat_delays_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Histogram of execution times of a single IO heartbeat check",
   "type": "heatmap",
   "description": "This histogram is updated whenever the io heartbeat runs its test in\nthe database directory. It writes a small file, syncs it to durable\nstorage, reads it, and then unlinks the file again. This test is done\nperiodically to ensure that the underlying volume is usable and performs\nreasonably well. The test can be switched off explicitly with the flag\n`--database.io-heartbeat=false`, but the default is `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_ioheartbeat_duration_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Histogram of execution times of a single IO heartbeat check (count of events per second)",
   "type": "graph",
   "description": "This histogram is updated whenever the io heartbeat runs its test in\nthe database directory. It writes a small file, syncs it to durable\nstorage, reads it, and then unlinks the file again. This test is done\nperiodically to ensure that the underlying volume is usable and performs\nreasonably well. The test can be switched off explicitly with the flag\n`--database.io-heartbeat=false`, but the default is `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(arangodb_ioheartbeat_duration_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Histogram of execution times of a single IO heartbeat check (average per second)",
   "type": "graph",
   "description": "This histogram is updated whenever the io heartbeat runs its test in\nthe database directory. It writes a small file, syncs it to durable\nstorage, reads it, and then unlinks the file again. This test is done\nperiodically to ensure that the underlying volume is usable and performs\nreasonably well. The test can be switched off explicitly with the flag\n`--database.io-heartbeat=false`, but the default is `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(arangodb_ioheartbeat_duration_sum[3m]) / rate(arangodb_ioheartbeat_duration_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of failures in the io heartbeat test",
   "type": "graph",
   "description": "This counter is increased whenever the io heartbeat encounters a problem\nwhen writing a small file to the database directory, reading it and then\nremoving it again. This test is done\nperiodically to ensure that the underlying volume is usable. The test can\nbe switched off explicitly with the flag `--database.io-heartbeat=false`,\nbut the default is `true`. Furthermore, every such failure leads to a\nline in the log at INFO level for the `ENGINES` topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(arangodb_ioheartbeat_failures_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "AQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Total number of AQL queries finished",
   "type": "graph",
   "description": "Total number of AQL queries finished.\nThis metric was named `arangodb_aql_all_query` in previous\nversions of ArangoDB.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_all_query_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Current number of AQL queries executing",
   "type": "graph",
   "description": "Current number of AQL queries executing.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "arangodb_aql_current_query", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Total memory limit for all AQL queries combined",
   "type": "graph",
   "description": "Total memory limit for all AQL queries combined, in bytes.\nIf this value is reported as `0`, it means there is no total memory\nlimit in place for AQL queries. The value can be adjusted by the setting\nthe `--query.global-memory-limit` startup option.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "arangodb_aql_global_memory_limit",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total memory usage of all AQL queries executing; granularity: 32768 bytes steps",
   "type": "graph",
   "description": "Total memory usage of all AQL queries currently executing.\nThe granularity of this metric is steps of 32768 bytes. The current\nmemory usage of all AQL queries will be compared against the configured\nlimit in the `--query.global-memory-limit` startup option.\nIf the startup option has a value of `0`, then no global memory limit\nwill be enforced. If the startup option has a non-zero value, queries\nwill be aborted once the total query memory usage goes above the configured\nlimit.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "arangodb_aql_global_memory_usage",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of times the global query memory limit threshold was reached",
   "type": "graph",
   "description": "Total number of times the global query memory limit threshold was reached.\nThis can happen if all running AQL queries in total try to use more memory than\nconfigured via the `--query.global-memory-limit` startup option.\nEvery time this counter will increase, an AQL query will have aborted with a\n\"resource limit exceeded\" error.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_global_query_memory_limit_reached_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of times a local query memory limit threshold was reached",
   "type": "graph",
   "description": "Total number of times a local query memory limit threshold was reached, i.e.\na single query tried to allocate more memory than configured in the query's\n`memoryLimit` attribute or the value configured via the startup option\n`--query.memory-limit`.\nEvery time this counter will increase, an AQL query will have aborted with a\n\"resource limit exceeded\" error.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_local_query_memory_limit_reached_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Execution time histogram for all AQL queries",
   "type": "heatmap",
   "description": "Execution time histogram for all AQL queries, in seconds.\nThe histogram includes all slow queries.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_aql_query_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Execution time histogram for all AQL queries (count of events per second)",
   "type": "graph",
   "description": "Execution time histogram for all AQL queries, in seconds.\nThe histogram includes all slow queries.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_query_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Execution time histogram for all AQL queries (average per second)",
   "type": "graph",
   "description": "Execution time histogram for all AQL queries, in seconds.\nThe histogram includes all slow queries.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_query_time_sum[3m]) / rate(arangodb_aql_query_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Execution time histogram for slow AQL queries",
   "type": "heatmap",
   "description": "Execution time histogram for slow AQL queries, in seconds.\nQueries are considered \"slow\" if their execution time is above the\nthreshold configured in the startup options `--query.slow-threshold`\nor `--query.slow-streaming-threshold`, resp.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_aql_slow_query_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Execution time histogram for slow AQL queries (count of events per second)",
   "type": "graph",
   "description": "Execution time histogram for slow AQL queries, in seconds.\nQueries are considered \"slow\" if their execution time is above the\nthreshold configured in the startup options `--query.slow-threshold`\nor `--query.slow-streaming-threshold`, resp.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_slow_query_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Execution time histogram for slow AQL queries (average per second)",
   "type": "graph",
   "description": "Execution time histogram for slow AQL queries, in seconds.\nQueries are considered \"slow\" if their execution time is above the\nthreshold configured in the startup options `--query.slow-threshold`\nor `--query.slow-streaming-threshold`, resp.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_slow_query_time_sum[3m]) / rate(arangodb_aql_slow_query_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total execution time of all AQL queries",
   "type": "graph",
   "description": "Total execution time of all AQL queries, in milliseconds,\nincluding all slow queries.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "rate(arangodb_aql_total_query_time_msec_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Total amount of collection lock acquisition time",
   "type": "graph",
   "description": "Total amount of time it took to acquire collection/shard locks for\nwrite operations, summed up for all collections/shards. Will not be increased\nfor any read operations.\nThe value is measured in microseconds.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "rate(arangodb_collection_lock_acquisition_micros_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of transactions using sequential locking of collections to avoid deadlocking",
   "type": "graph",
   "description": "Number of transactions using sequential locking of collections to avoid deadlocking.\nBy default, a Coordinator will try to lock all shards of a collection in parallel.\nThis approach is normally fast but can cause deadlocks with other transactions that\nlock the same shards in a different order. In case such a deadlock is detected, the\nCoordinator will abort the lock round and start a new one that locks all shards in\nsequential order. This will avoid deadlocks, but has a higher setup overhead.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "rate(arangodb_collection_lock_sequential_mode_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of timeouts when trying to acquire collection exclusive locks",
   "type": "graph",
   "description": "Number of timeouts when trying to acquire collection exclusive locks.\nThis counter will be increased whenever an exclusive collection lock\ncannot be acquired within the configured lock timeout.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "rate(arangodb_collection_lock_timeouts_exclusive_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of timeouts when trying to acquire collection write locks",
   "type": "graph",
   "description": "Number of timeouts when trying to acquire collection write locks.\nThis counter will be increased whenever a collection write lock\ncannot be acquired within the configured lock timeout.\nThis can only happen if writes on a collection are locked out by\nother operations on the collection that use an exclusive lock. Writes\nare not locked out by other, non-exclusively locked writes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "rate(arangodb_collection_lock_timeouts_write_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in collection truncate operations",
   "type": "heatmap",
   "description": "Total time spent in collection truncate operations, including both\nuser-initiated truncate operations and truncate operations\nexecuted by the synchronous replication on followers.\nNote that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_collection_truncate_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Total time spent in collection truncate operations (count of events per second)",
   "type": "graph",
   "description": "Total time spent in collection truncate operations, including both\nuser-initiated truncate operations and truncate operations\nexecuted by the synchronous replication on followers.\nNote that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "rate(arangodb_collection_truncate_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in collection truncate operations (average per second)",
   "type": "graph",
   "description": "Total time spent in collection truncate operations, including both\nuser-initiated truncate operations and truncate operations\nexecuted by the synchronous replication on followers.\nNote that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "rate(arangodb_collection_truncate_time_sum[3m]) / rate(arangodb_collection_truncate_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of collection truncate operations (excluding synchronous replication)",
   "type": "graph",
   "description": "Total number of collection truncate operations on leaders (excluding synchronous\nreplication). Note that this metric is only present when the command\nline option `--server.export-read-write-metrics` is set to `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "rate(arangodb_collection_truncates_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document insert operations",
   "type": "heatmap",
   "description": "Total time spent in document insert operations, including both\nuser-initiated insert operations and insert operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_insert_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Total time spent in document insert operations (count of events per second)",
   "type": "graph",
   "description": "Total time spent in document insert operations, including both\nuser-initiated insert operations and insert operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "rate(arangodb_document_insert_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document insert operations (average per second)",
   "type": "graph",
   "description": "Total time spent in document insert operations, including both\nuser-initiated insert operations and insert operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "rate(arangodb_document_insert_time_sum[3m]) / rate(arangodb_document_insert_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document read-by-primary-key operations",
   "type": "heatmap",
   "description": "Total time spent in document read-by-primary-key operations. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_read_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Total time spent in document read-by-primary-key operations (count of events per second)",
   "type": "graph",
   "description": "Total time spent in document read-by-primary-key operations. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "rate(arangodb_document_read_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document read-by-primary-key operations (average per second)",
   "type": "graph",
   "description": "Total time spent in document read-by-primary-key operations. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "rate(arangodb_document_read_time_sum[3m]) / rate(arangodb_document_read_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document remove operations",
   "type": "heatmap",
   "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_remove_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Total time spent in document remove operations (count of events per second)",
   "type": "graph",
   "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "expr": "rate(arangodb_document_remove_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document remove operations (average per second)",
   "type": "graph",
   "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "rate(arangodb_document_remove_time_sum[3m]) / rate(arangodb_document_remove_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document replace operations",
   "type": "heatmap",
   "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_replace_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Total time spent in document replace operations (count of events per second)",
   "type": "graph",
   "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "rate(arangodb_document_replace_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document replace operations (average per second)",
   "type": "graph",
   "description": "Total time spent in document replace operations, including both\nuser-initiated replace operations and replace operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "targets": [
    {
     "expr": "rate(arangodb_document_replace_time_sum[3m]) / rate(arangodb_document_replace_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document update operations",
   "type": "heatmap",
   "description": "Total time spent in document update operations, including both\nuser-initiated update operations and update operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_document_update_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Total time spent in document update operations (count of events per second)",
   "type": "graph",
   "description": "Total time spent in document update operations, including both\nuser-initiated update operations and update operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "rate(arangodb_document_update_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time spent in document update operations (average per second)",
   "type": "graph",
   "description": "Total time spent in document update operations, including both\nuser-initiated update operations and update operations executed by\nthe synchronous replication on followers. This metric\nis only present if the option `--server.export-read-write-metrics` is set\nto `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "rate(arangodb_document_update_time_sum[3m]) / rate(arangodb_document_update_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of document write operations (excluding synchronous replication)",
   "type": "graph",
   "description": "Total number of document write operations (insert, update, replace, remove) on\nleaders, excluding writes by the synchronous replication on followers.\nThis metric is only present if the option `--server.export-read-write-metrics`\nis set to `true`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "targets": [
    {
     "expr": "rate(arangodb_document_writes_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of read transactions",
   "type": "graph",
   "description": "Total number of read-only transactions. In the cluster, this metric will\nbe collected separately for transactions on Coordinators and the\ntransaction counterparts on leaders and followers.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "targets": [
    {
     "expr": "rate(arangodb_read_transactions_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of transactions aborted",
   "type": "graph",
   "description": "Total number of transactions aborted. In the cluster, this metric will\nbe collected separately for transactions on Coordinators and the\ntransaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_aborted` in previous\nversions of ArangoDB.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
   "targets": [
    {
     "expr": "rate(arangodb_transactions_aborted_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of transactions committed",
   "type": "graph",
   "description": "Total number of transactions committed. In the cluster, this metric will\nbe collected separately for transactions on Coordinators and the\ntransaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_committed` in previous\nversions of ArangoDB.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
   "targets": [
    {
     "expr": "rate(arangodb_transactions_committed_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of expired transactions",
   "type": "graph",
   "description": "Total number of expired transactions, i.e. transactions that have\nbeen begun but that were automatically garbage-collected due to\ninactivity within the transactions' time-to-live (TTL) period.\nIn the cluster, this metric will be collected separately for transactions\non Coordinators and the transaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_expired` in previous\nversions of ArangoDB.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 203 },
   "targets": [
    {
     "expr": "rate(arangodb_transactions_expired_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of transactions started",
   "type": "graph",
   "description": "Total number of transactions started/begun. In the cluster, this metric will\nbe collected separately for transactions on Coordinators and the\ntransaction counterparts on leaders and followers.\nThis metric was named `arangodb_transactions_started` in previous\nversions of ArangoDB.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
   "targets": [
    {
     "expr": "rate(arangodb_transactions_started_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Bytes received for a request (count of events per second)",
   "type": "graph",
   "description": "Histogram of the received request sizes in bytes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 211 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_bytes_received_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 219 } },
  {
   "title": "Bytes received for a request",
   "type": "heatmap",
   "description": "Histogram of the received request sizes in bytes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_bytes_received_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Bytes sent for a request",
   "type": "heatmap",
   "description": "Histogram of the sent response sizes in bytes\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_bytes_sent_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Bytes received for a request (average per second)",
   "type": "graph",
   "description": "Histogram of the received request sizes in bytes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_bytes_received_sum[3m]) / rate(arangodb_client_connection_statistics_bytes_received_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Bytes sent for a request (average per second)",
   "type": "graph",
   "description": "Histogram of the sent response sizes in bytes\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_bytes_sent_sum[3m]) / rate(arangodb_client_connection_statistics_bytes_sent_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Bytes sent for a request (count of events per second)",
   "type": "graph",
   "description": "Histogram of the sent response sizes in bytes\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_bytes_sent_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "I/O time needed to answer a request",
   "type": "heatmap",
   "description": "Histogram of I/O times needed to answer a request. This includes the time\nrequired to read the incoming request as well as the time required to send\nthe response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_io_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "The number of client connections that are currently open",
   "type": "graph",
   "description": "The number of client connections that are currently open.\nNote: this metric considers only HTTP and HTTP/2 connections, but not VST\nconnections.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "I/O time needed to answer a request (average per second)",
   "type": "graph",
   "description": "Histogram of I/O times needed to answer a request. This includes the time\nrequired to read the incoming request as well as the time required to send\nthe response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 244 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_io_time_sum[3m]) / rate(arangodb_client_connection_statistics_io_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "I/O time needed to answer a request (count of events per second)",
   "type": "graph",
   "description": "Histogram of I/O times needed to answer a request. This includes the time\nrequired to read the incoming request as well as the time required to send\nthe response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 252 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_io_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Queueing time needed for requests (count of events per second)",
   "type": "graph",
   "description": "Histogram of the time requests are spending on a queue waiting to be\nprocessed. The overwhelming majority of these times should be clearly\nsub-second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 252 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_queue_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Queueing time needed for requests",
   "type": "heatmap",
   "description": "Histogram of the time requests are spending on a queue waiting to be\nprocessed. The overwhelming majority of these times should be clearly\nsub-second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_queue_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Request time needed to answer a request",
   "type": "heatmap",
   "description": "Histogram of the time required to actually process a request. This does not\ninclude the time required to read the incoming request, the time the request\nis sitting on the queue, or the time required to send the response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 260 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_request_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Queueing time needed for requests (average per second)",
   "type": "graph",
   "description": "Histogram of the time requests are spending on a queue waiting to be\nprocessed. The overwhelming majority of these times should be clearly\nsub-second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 268 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_queue_time_sum[3m]) / rate(arangodb_client_connection_statistics_queue_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Request time needed to answer a request (average per second)",
   "type": "graph",
   "description": "Histogram of the time required to actually process a request. This does not\ninclude the time required to read the incoming request, the time the request\nis sitting on the queue, or the time required to send the response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 268 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_request_time_sum[3m]) / rate(arangodb_client_connection_statistics_request_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Request time needed to answer a request (count of events per second)",
   "type": "graph",
   "description": "Histogram of the time required to actually process a request. This does not\ninclude the time required to read the incoming request, the time the request\nis sitting on the queue, or the time required to send the response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 276 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_request_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time needed to answer a request (count of events per second)",
   "type": "graph",
   "description": "Histogram of the total times required to process a request. This includes\nthe time required to read the incoming request, the time the request is\nsitting in the queue, the time to actually process the request, and the\ntime required to send the response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 276 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_total_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time needed to answer a request",
   "type": "heatmap",
   "description": "Histogram of the total times required to process a request. This includes\nthe time required to read the incoming request, the time the request is\nsitting in the queue, the time to actually process the request, and the\ntime required to send the response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 284 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_client_connection_statistics_total_time_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Number of asynchronously executed HTTP requests",
   "type": "graph",
   "description": "This counter reflects the total number of **asynchronous** HTTP (or VST)\nrequests which have hit this particular instance of `arangod`. Asynchronous\nrefers to the fact that the response is not sent with the HTTP response,\nbut is rather queried separately using the `/_api/jobs` API.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 284 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_async_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total time needed to answer a request (average per second)",
   "type": "graph",
   "description": "Histogram of the total times required to process a request. This includes\nthe time required to read the incoming request, the time the request is\nsitting in the queue, the time to actually process the request, and the\ntime required to send the response.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 292 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_total_time_sum[3m]) / rate(arangodb_client_connection_statistics_total_time_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of HTTP GET requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **GET**\nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 292 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_get_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of HTTP DELETE requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **DELETE**\nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 300 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_delete_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of HTTP OPTIONS requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **OPTIONS**\nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 300 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_options_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of HTTP HEAD requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **HEAD**\nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 308 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_head_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of HTTP POST requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **POST**\nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 308 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_post_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of HTTP PATCH requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **PATCH**\nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 316 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_patch_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of other HTTP requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **other**\nor **ILLEGAL** requests which have hit this particular instance of\n`arangod`. These are all requests, which are not one of the following:\n`DELETE`, `GET`, `HEAD`, `POST`, `PUT`, `OPTIONS`, `PATCH`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 316 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_other_http_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of HTTP PUT requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) **PUT**\nrequests which have hit this particular instance of `arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 324 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_put_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) requests which\nhave hit this particular instance of `arangod`. Note that this counter\nis ever growing during the lifetime of the `arangod` process. However,\nwhen the process is restarted, it starts from scratch. In the Grafana\ndashboards, it is usually visualized as a rate per second, averaged\nwith a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 324 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_total_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests executed by superuser/JWT",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST)\nrequests that have been authenticated with the JWT superuser token,\nwhich have hit this particular instance of\n`arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 332 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_superuser_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of intermediate commits performed in transactions",
   "type": "graph",
   "description": "Number of intermediate commits performed in transactions.\nAn intermediate commit happens if a logical transaction needs to be\nsplit into multiple physical transaction because of the volume of data\nhandled in the transaction. The thresholds for when to perform an\nintermediate commit can be controlled by startup options\n`--rocksdb.intermediate-commit-count` (number of write operations after\nwhich an intermediate commit is triggered) and `--rocksdb.intermediate-commit-size`\n(cumulated size of write operations after which an intermediate commit is triggered).\nThe values can also be overridden for individual transactions.\nThis metric was named `arangodb_intermediate_commits` in previous\nversions of ArangoDb.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 332 },
   "targets": [
    {
     "expr": "rate(arangodb_intermediate_commits_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests executed by user clients",
   "type": "graph",
   "description": "This counter reflects the total number of HTTP (or VST) requests\nthat have been authenticated for some user (as opposed to with the\nJWT superuser token), which have hit this particular instance of\n`arangod`.\n\nNote that this counter is ever growing during the lifetime of the\n`arangod` process. However, when the process is restarted, it starts\nfrom scratch. In the Grafana dashboards, it is usually visualized as a\nrate per second, averaged with a sliding window of a minute.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 340 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_user_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of minor page faults",
   "type": "graph",
   "description": "The number of minor faults the process has made which have not required\nloading a memory page from disk. This figure is not reported on Windows.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 340 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_minor_page_faults_total",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of major page faults",
   "type": "graph",
   "description": "On Windows, this figure contains the total number of page faults.\nOn other system, this figure contains the number of major faults the\nprocess has made which have required loading a memory page from disk.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 348 },
   "targets": [
    {
     "expr": "rate(arangodb_process_statistics_major_page_faults_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Resident set size",
   "type": "graph",
   "description": "The total size of the number of pages the process has in real memory.\nThis is just the pages which count toward text, data, or stack space.\nThis does not include pages which have not been demand-loaded in, or\nwhich are swapped out. The resident set size is reported in bytes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 348 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_resident_set_size",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "graph",
   "description": "Number of threads in the arangod process.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 356 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Process system time",
   "type": "graph",
   "description": "Amount of time that this process has been scheduled in kernel mode,\nmeasured in seconds.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 356 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_system_time",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Resident set size as fraction of system memory",
   "type": "graph",
   "description": "The relative size of the number of pages the process has in real\nmemory compared to system memory. This is just the pages which count\ntoward text, data, or stack space. This does not include pages which\nhave not been demand-loaded in, or which are swapped out. The value is a\nratio between 0.00 and 1.00.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 364 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_resident_set_size_percent",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Virtual memory size",
   "type": "graph",
   "description": "On Windows, this figure contains the total amount of memory that the\nmemory manager has committed for the arangod process. On other systems,\nthis figure contains the size of the virtual memory the process is\nusing.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 364 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_virtual_memory_size",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Process user time",
   "type": "graph",
   "description": "Amount of time that this process has been scheduled in user mode,\nmeasured in seconds.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 372 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_user_time",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Body size in bytes for HTTP/1.1 requests (count of events per second)",
   "type": "graph",
   "description": "Histogram of the body sizes of the received HTTP/1.1 requests in bytes.\nNote that this does not account for the header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 372 },
   "targets": [
    {
     "expr": "rate(arangodb_request_body_size_http1_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Body size in bytes for HTTP/1.1 requests",
   "type": "heatmap",
   "description": "Histogram of the body sizes of the received HTTP/1.1 requests in bytes.\nNote that this does not account for the header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 380 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_request_body_size_http1_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Body size in bytes for HTTP/2 requests",
   "type": "heatmap",
   "description": "Histogram of the body sizes of the received HTTP/2 requests in bytes.\nNote that this does not account for the header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 380 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_request_body_size_http2_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Body size in bytes for HTTP/1.1 requests (average per second)",
   "type": "graph",
   "description": "Histogram of the body sizes of the received HTTP/1.1 requests in bytes.\nNote that this does not account for the header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 388 },
   "targets": [
    {
     "expr": "rate(arangodb_request_body_size_http1_sum[3m]) / rate(arangodb_request_body_size_http1_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Body size in bytes for HTTP/2 requests (average per second)",
   "type": "graph",
   "description": "Histogram of the body sizes of the received HTTP/2 requests in bytes.\nNote that this does not account for the header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 388 },
   "targets": [
    {
     "expr": "rate(arangodb_request_body_size_http2_sum[3m]) / rate(arangodb_request_body_size_http2_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Body size in bytes for HTTP/2 requests (count of events per second)",
   "type": "graph",
   "description": "Histogram of the body sizes of the received HTTP/2 requests in bytes.\nNote that this does not account for the header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 396 },
   "targets": [
    {
     "expr": "rate(arangodb_request_body_size_http2_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Body size in bytes for VST requests (count of events per second)",
   "type": "graph",
   "description": "Histogram of the body sizes of the received VST requests in bytes.\nNote that this does include the binary header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 396 },
   "targets": [
    {
     "expr": "rate(arangodb_request_body_size_vst_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Body size in bytes for VST requests",
   "type": "heatmap",
   "description": "Histogram of the body sizes of the received VST requests in bytes.\nNote that this does include the binary header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 404 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_request_body_size_vst_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Number of CPU cores visible to the arangod process",
   "type": "graph",
   "description": "Number of CPU cores visible to the arangod process, unless the\nenvironment variable `ARANGODB_OVERRIDE_DETECTED_NUMBER_OF_CORES`\nis set. In that case, the environment variable's value will be reported.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 404 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_cpu_cores",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Body size in bytes for VST requests (average per second)",
   "type": "graph",
   "description": "Histogram of the body sizes of the received VST requests in bytes.\nNote that this does include the binary header.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 412 },
   "targets": [
    {
     "expr": "rate(arangodb_request_body_size_vst_sum[3m]) / rate(arangodb_request_body_size_vst_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Percentage of time that the system CPUs have been waiting for I/O",
   "type": "graph",
   "description": "Percentage of time that the system CPUs have been waiting for I/O, as\na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 412 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_iowait_percent",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Percentage of time that the system CPUs have been idle",
   "type": "graph",
   "description": "Percentage of time that the system CPUs have been idle, as\na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 420 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_idle_percent",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of seconds elapsed since server start",
   "type": "graph",
   "description": "Number of seconds elapsed since server start, including fractional\nseconds.\nThis metric was named `arangodb_server_statistics_server_uptime`\nin previous versions of ArangoDB.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 420 },
   "targets": [
    {
     "expr": "rate(arangodb_server_statistics_server_uptime_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Physical memory in bytes",
   "type": "graph",
   "description": "Physical memory of the system in bytes, as reported by the operating system\nunless the environment variable `ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY`\nis set. In that case, the environment variable's value will be reported.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 428 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_physical_memory",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Percentage of time that the system CPUs have spent in user mode",
   "type": "graph",
   "description": "Percentage of time that the system CPUs have spent in user mode, as\na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 428 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_user_percent",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Percentage of time that the system CPUs have spent in kernel mode",
   "type": "graph",
   "description": "Percentage of time that the system CPUs have spent in kernel mode, as\na value between 0 and 100, and as reported by the operating system.\nThis metric is only reported on some operating systems.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 436 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_system_percent",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of V8 contexts currently busy",
   "type": "graph",
   "description": "Number of V8 contexts currently busy, that means, they are currently\nworking on some JavaScript task. Normally, only Coordinators and\nsingle servers should have V8 contexts, for DB-Servers and Agents the\nvalue is always zero.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 436 },
   "targets": [
    { "expr": "arangodb_v8_context_busy", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Number of V8 contexts currently alive",
   "type": "graph",
   "description": "Number of V8 contexts currently alive. Normally, only Coordinators and\nsingle servers should have V8 contexts, for DB-Servers and Agents the\nvalue is always zero.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 444 },
   "targets": [
    { "expr": "arangodb_v8_context_alive", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Number of V8 contexts currently free",
   "type": "graph",
   "description": "This gauge reflects the number of V8 contexts that are currently free.\nIf this number drops to 0 there might be a shortage of V8 contexts.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 444 },
   "targets": [
    { "expr": "arangodb_v8_context_free", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Number of V8 contexts currently dirty",
   "type": "graph",
   "description": "This gauge reflects the number of V8 contexts that are currently dirty.\nA V8 context is dirty, if it has executed JavaScript for some time and\nis due for a garbage collection.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 452 },
   "targets": [
    { "expr": "arangodb_v8_context_dirty", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Minimum number of concurrent V8 contexts",
   "type": "graph",
   "description": "This is the minimum number of concurrent V8 contexts. This is limited\nby a server option. V8 contexts are created and destroyed as needed\nbut there are never fewer than the limit shown in this metric.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 452 },
   "targets": [
    { "expr": "arangodb_v8_context_min", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Maximum number of concurrent V8 contexts",
   "type": "graph",
   "description": "This is the maximum number of concurrent V8 contexts. This is limited\nby a server option, since V8 contexts can use a lot of RAM. V8 contexts\nare created and destroyed as needed up to the limit shown in this metric.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 460 },
   "targets": [
    { "expr": "arangodb_v8_context_max", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 468 } },
  {
   "title": "Total number of documents replicated in initial asynchronous phase",
   "type": "graph",
   "description": "During initial replication the existing data from the leader is copied asynchronously\nover to new shards. The amount of documents transported to this server, as a replica for\na shard, is counted here.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 469 },
   "targets": [
    {
     "expr": "rate(arangodb_replication_dump_documents_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total memory usage of all revision trees (both hibernated and uncompressed)",
   "type": "graph",
   "description": "Total memory usage of all revision trees for collections/shards.\nThe revision trees of collections/shards are normally present\nin RAM in an uncompressed state. However, to reduce the memory\nusage of keeping all revision trees in RAM at the same time, \nrevision trees can be put into \"hibernation\" mode. Any inactive\nrevision tree will automatically be hibernated by ArangoDB after\na while. For the hibernation step, a revision tree will be \ncompressed in RAM, and only the compressed version is then kept.\nLater accesses of a compressed revision tree require uncompressing\nthe tree again. \nThis metrics reports the total memory usage of all revision trees,\nincluding both the hibernated and uncompressed forms).\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 469 },
   "targets": [
    {
     "expr": "arangodb_revision_tree_memory_usage",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of leader shards on this machine",
   "type": "graph",
   "description": "Number of leader shards on this machine. Every shard has a leader and\npotentially multiple followers.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 477 },
   "targets": [
    { "expr": "arangodb_shards_leader_number", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Number of shards not replicated at all",
   "type": "graph",
   "description": "Number of shards not replicated at all. This is counted for all shards\nfor which this server is currently the leader. The number is increased\nby one for every shards for which no follower is in sync.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 477 },
   "targets": [
    { "expr": "arangodb_shards_not_replicated", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Number of shards on this machine",
   "type": "graph",
   "description": "Number of shards on this machine. Every shard has a leader and\npotentially multiple followers. This metric counts both leader and\nfollower shards.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 485 },
   "targets": [
    { "expr": "arangodb_shards_number", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Number of leader shards not fully replicated",
   "type": "graph",
   "description": "Number of leader shards not fully replicated. This is counted for all\nshards for which this server is currently the leader. The number is\nincreased by one for every shards for which not all followers are in sync.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 485 },
   "targets": [
    { "expr": "arangodb_shards_out_of_sync", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 493 } },
  {
   "title": "Total number of errors logged",
   "type": "graph",
   "description": "Total number of errors (ERR messages) logged by the logger. \n\nIf a problem is encountered which is fatal to some operation, but not for\nthe service or the application as a whole, then an _error is logged.\n\nReasons for log entries of this severity are for example include missing\ndata, inability to open required files, incorrect connection strings,\nmissing services.\n\nIf an error is logged then it should be taken seriously as it may require \nuser intervention to solve.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 494 },
   "targets": [
    {
     "expr": "rate(arangodb_logger_errors_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of warnings logged",
   "type": "graph",
   "description": "Total number of warnings (WARN messages) logged by the logger, \nincluding startup warnings.\n\nWarnings might indicate problems, or might not. For example, \nexpected transient environmental conditions such as short loss of \nnetwork or database connectivity are logged as warnings, not errors. \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 494 },
   "targets": [
    {
     "expr": "rate(arangodb_logger_warnings_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "RocksDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 502 } },
  {
   "title": "Number of times RocksDB has entered a stalled (slowed) write state",
   "type": "graph",
   "description": "This counter reflects the number of times RocksDB was observed by\nArangoDB to have entered a stalled (slowed) write state.\n\nIf the RocksDB background threads which do cleanup and compaction\ncannot keep up with the writing, then RocksDB first throttles its\nwrite rate (\"write stall\") and later stops the writing entirely\n(\"write stop\"). Both are suboptimal, since the write rate is too high.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 503 },
   "targets": [
    {
     "expr": "rate(arangodb_rocksdb_write_stalls_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of times RocksDB has entered a stopped write state",
   "type": "graph",
   "description": "This counter reflects the number of times RocksDB was observed by\nArangoDB to have entered a stopped write state.\n\nIf the RocksDB background threads which do cleanup and compaction\ncannot keep up with the writing, then RocksDB first throttles its\nwrite rate (\"write stall\") and later stops the writing entirely\n(\"write stop\"). Both are suboptimal, since the write rate is too high,\nbut write stops are considerably worse, since they can lead to service\nunavailability.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 503 },
   "targets": [
    {
     "expr": "rate(arangodb_rocksdb_write_stops_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "RocksDB metric \"background-errors\"",
   "type": "graph",
   "description": "This metric indicates whether RocksDB currently is in read-only\nmode, due to a background error. If RocksDB is in read-only mode,\nthis metric will have a value of \"1\". When in read-only mode, all\nwrites into RocksDB will fail. When RocksDB is in normal operations\nmode, this metric will have a value of \"0\".\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 511 },
   "targets": [
    { "expr": "rocksdb_read_only", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  },
  {
   "title": "Number of requests forwarded to another Coordinator",
   "type": "graph",
   "description": "Number of requests forwarded to another Coordinator.\nRequest forwarding can happen in load-balanced setups,\nwhen one Coordinator receives and forwards requests\nthat can only be handled by a different Coordinator.\nThis includes requests for streaming transactions,\nAQL, query cursors, Pregel jobs and some others.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 511 },
   "targets": [
    {
     "expr": "rate(arangodb_network_forwarded_requests_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 519 } },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 520 } },
  {
   "title": "Request time for Agency requests",
   "type": "heatmap",
   "description": "This histogram shows how long requests to the Agency took.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 521 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_agencycomm_request_time_msec_bucket[3m])) by (le))"
    }
   ]
  },
  {
   "title": "Request time for Agency requests (count of events per second)",
   "type": "graph",
   "description": "This histogram shows how long requests to the Agency took.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 521 },
   "targets": [
    {
     "expr": "rate(arangodb_agencycomm_request_time_msec_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Request time for Agency requests (average per second)",
   "type": "graph",
   "description": "This histogram shows how long requests to the Agency took.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 529 },
   "targets": [
    {
     "expr": "rate(arangodb_agencycomm_request_time_msec_sum[3m]) / rate(arangodb_agencycomm_request_time_msec_count[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of outgoing internal requests in flight",
   "type": "graph",
   "description": "Number of outgoing internal requests in flight. This metric is increased\nwhenever any cluster-internal request is about to be sent via the underlying\nconnection pool, and is decreased whenever a response for such a request is\nreceived or the request runs into a timeout.\nThis metric provides an estimate of the fan-out of operations. For example,\na user operation on a collection with a single shard will normally lead to\na single internal request (plus replication), whereas an operation on a\ncollection with 10 shards may lead to a fan-out of 10 (plus replication).\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 529 },
   "targets": [
    {
     "expr": "arangodb_network_requests_in_flight",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of internal requests that have timed out",
   "type": "graph",
   "description": "Number of internal requests that have timed out. This metric is increased\nwhenever any cluster-internal request executed in the underlying connection\npool runs into a timeout.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 537 },
   "targets": [
    {
     "expr": "rate(arangodb_network_request_timeouts_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of V8 context enter failures",
   "type": "graph",
   "description": "Total number of V8 context enter failures. A context receives a context\nenter event every time it begins to execute some JavaScript. If no\ncontext is available at such a time the system waits for 60s for a\ncontext to become free. If this does not happen within the 60s, the\ncontext enter event fails, a warning is logged and this counter is\nincreased by one.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 537 },
   "targets": [
    {
     "expr": "rate(arangodb_v8_context_enter_failures_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "V8", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 545 } },
  {
   "title": "Total number of V8 contexts ever created",
   "type": "graph",
   "description": "This counter reflects the total number of V8 contexts ever created. It is\nOK if this number keeps growing since the V8 contexts are created and\ndestroyed as needed. In rare cases a high fluctuation can indicate\nsome unfortunate usage pattern.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 546 },
   "targets": [
    {
     "expr": "rate(arangodb_v8_context_created_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Accumulated total time for creating V8 contexts",
   "type": "graph",
   "description": "This counter reflects the accumulated total time for creating V8\ncontexts, in milliseconds. It is OK if this number keeps growing since\nthe V8 contexts are created and destroyed as needed. In rare cases a\nhigh fluctuation can indicate some unfortunate usage pattern.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 546 },
   "targets": [
    {
     "expr": "rate(arangodb_v8_context_creation_time_msec_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of V8 contexts ever destroyed",
   "type": "graph",
   "description": "This counter reflects the total number of V8 contexts ever destroyed.\nIt is OK if this number keeps growing since the V8 contexts are\ncreated and destroyed as needed. In rare cases a high fluctuation can\nindicate some unfortunate usage pattern.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 554 },
   "targets": [
    {
     "expr": "rate(arangodb_v8_context_destroyed_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of V8 context exit events",
   "type": "graph",
   "description": "This counter reflects the total number of V8 context exit events.\nA context receives a context exit event every time it finishes to\nexecute some JavaScript.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 554 },
   "targets": [
    {
     "expr": "rate(arangodb_v8_context_exited_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of V8 context enter events",
   "type": "graph",
   "description": "Total number of V8 context enter events. A context receives a context\nenter event every time it begins to execute some JavaScript. This number\nis a rough estimate as to how much JavaScript the server executes.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 562 },
   "targets": [
    {
     "expr": "rate(arangodb_v8_context_entered_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Current number of working threads",
   "type": "graph",
   "description": "The current number of threads actually working on some job (i.e., not\nspinning while waiting for new work).\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 562 },
   "targets": [
    {
     "expr": "arangodb_scheduler_num_working_threads",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "Agency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 570 } },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 571 } },
  {
   "title": "Last recorded dequeue time for a low priority queue item",
   "type": "graph",
   "description": "Last recorded dequeue time for a low priority queue item, i.e., the amount of\ntime the job was sitting in the queue. If there is nothing to do for a long\ntime, this metric will be reset to zero.\nA large value for this metric indicates that the server is under heavy load\nand low priority jobs cannot be dequeued in a timely manner\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 572 },
   "targets": [
    {
     "expr": "arangodb_scheduler_low_prio_queue_last_dequeue_time",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of awake worker threads",
   "type": "graph",
   "description": "The number of worker threads currently working on some job or spinning while\nwaiting for new work (i.e., not sleeping).\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 572 },
   "targets": [
    {
     "expr": "arangodb_scheduler_num_awake_threads",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Current number of worker threads",
   "type": "graph",
   "description": "The number of worker threads currently started. Worker threads can be started\nand stopped dynamically based on the server load.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 580 },
   "targets": [
    {
     "expr": "arangodb_scheduler_num_worker_threads",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of tasks dropped and not added to internal queue",
   "type": "graph",
   "description": "Number of tasks dropped because the queue was already full. The queue capacities\ncan be configured via the startup options `--server.scheduler-queue-size`,\n`--server.prio1-size`, `--server.prio2-size` and `--server.maximal-queue-size`.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 580 },
   "targets": [
    {
     "expr": "rate(arangodb_scheduler_queue_full_failures_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Total number of ongoing RestHandlers coming from the low priority queue",
   "type": "graph",
   "description": "Total number of low priority jobs currently being processed.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 588 },
   "targets": [
    {
     "expr": "arangodb_scheduler_ongoing_low_prio",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Number of tasks/requests dropped and not added to internal queue\ndue to the client-specified queue time requirements not being\nsatisfiable",
   "type": "graph",
   "description": "Number of tasks/requests dropped because the client-specified queue time\nrequirements, as indicated by client applications in the request header\n\"x-arango-queue-time-seconds\" could not be satisfied by the receiving \nserver instance. This happens when the actual time need to queue/dequeue\nrequests on the scheduler queue exceeds the maximum time value that the\nclient has specified in the request. \nWhenever this happens, the client application will get an HTTP 412 error \nresponse back with error code 21004 (\"queue time violated\").\nAlthough the metric is exposed on all instance types, it will very likely\nalways be 0 on DB servers, simply because coordinators do not forward the\n\"x-arango-queue-time-seconds\" when they send internal requests to DB\nservers.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 588 },
   "targets": [
    {
     "expr": "rate(arangodb_scheduler_queue_time_violations_total[3m])",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Server's internal queue length",
   "type": "graph",
   "description": "The total number of currently queued jobs in all queues.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 596 },
   "targets": [
    {
     "expr": "arangodb_scheduler_queue_length",
     "legendFormat": "{{instance}}:{{shortname}}"
    }
   ]
  },
  { "title": "Maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 604 } },
  { "title": "License", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 605 } },
  {
   "title": "This instance's license expiry in days",
   "type": "graph",
   "description": "This instance's remaining license validity time.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 606 },
   "targets": [
    { "expr": "arangodb_license_expires", "legendFormat": "{{instance}}:{{shortname}}" }
   ]
  }
 ]
}